import type { PermissionCode, RoleCode } from "@/lib/supabase/types";

export const ROLE_CODES = [
  "platform_admin",
  "organization_admin",
  "district_sped_admin",
  "building_admin",
  "program_admin",
  "intervention_specialist",
  "special_education_teacher",
  "related_service_provider",
  "school_psychologist",
  "case_manager",
  "paraprofessional",
  "read_only_reviewer",
] as const satisfies readonly RoleCode[];

export const PERMISSION_CODES = [
  "org.manage",
  "org.members.manage",
  "org.audit.read",
  "school.manage",
  "program.manage",
  "classroom.manage",
  "staff.assign",
  "student.create",
  "student.edit",
  "student.archive",
  "student.read",
  "iep.manage",
  "goal.manage",
  "goal.read",
  "progress.enter",
  "progress.finalize",
  "progress.read",
  "analytics.read",
] as const satisfies readonly PermissionCode[];

export const ROLE_LABELS: Record<RoleCode, string> = {
  platform_admin: "Platform administrator",
  organization_admin: "Organization administrator",
  district_sped_admin: "District special education administrator",
  building_admin: "Building administrator",
  program_admin: "Program administrator",
  intervention_specialist: "Intervention specialist",
  special_education_teacher: "Special education teacher",
  related_service_provider: "Related service provider",
  school_psychologist: "School psychologist",
  case_manager: "Case manager",
  paraprofessional: "Paraprofessional",
  read_only_reviewer: "Read-only reviewer",
};

export const PERMISSION_LABELS: Record<PermissionCode, string> = {
  "org.manage": "Manage organization",
  "org.members.manage": "Manage memberships",
  "org.audit.read": "Read audit events",
  "school.manage": "Manage schools",
  "program.manage": "Manage programs",
  "classroom.manage": "Manage classrooms",
  "staff.assign": "Assign staff",
  "student.create": "Create students",
  "student.edit": "Edit students",
  "student.archive": "Archive students",
  "student.read": "Read students",
  "iep.manage": "Manage IEP cycles",
  "goal.manage": "Manage goals",
  "goal.read": "Read goals",
  "progress.enter": "Enter progress data",
  "progress.finalize": "Finalize progress data",
  "progress.read": "Read progress data",
  "analytics.read": "Read analytics",
};

/**
 * Mirrors the grants in 202607280002_roles_permissions_profiles.sql.
 * Authorization still comes from RLS/RPC checks; this matrix is documentation
 * and a UI affordance for showing expected capabilities.
 */
export const ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionCode[]> = {
  platform_admin: [],
  organization_admin: PERMISSION_CODES,
  district_sped_admin: [
    "org.audit.read",
    "school.manage",
    "program.manage",
    "classroom.manage",
    "staff.assign",
    "student.create",
    "student.edit",
    "student.archive",
    "student.read",
    "iep.manage",
    "goal.manage",
    "goal.read",
    "progress.enter",
    "progress.finalize",
    "progress.read",
    "analytics.read",
  ],
  building_admin: [
    "school.manage",
    "classroom.manage",
    "staff.assign",
    "student.create",
    "student.edit",
    "student.read",
    "goal.read",
    "progress.read",
    "analytics.read",
  ],
  program_admin: [
    "program.manage",
    "classroom.manage",
    "staff.assign",
    "student.create",
    "student.edit",
    "student.read",
    "iep.manage",
    "goal.manage",
    "goal.read",
    "progress.enter",
    "progress.finalize",
    "progress.read",
    "analytics.read",
  ],
  intervention_specialist: [
    "student.read",
    "iep.manage",
    "goal.manage",
    "goal.read",
    "progress.enter",
    "progress.finalize",
    "progress.read",
    "analytics.read",
  ],
  special_education_teacher: [
    "student.read",
    "goal.read",
    "progress.enter",
    "progress.read",
    "analytics.read",
  ],
  related_service_provider: [
    "student.read",
    "goal.read",
    "progress.enter",
    "progress.read",
    "analytics.read",
  ],
  school_psychologist: ["student.read", "goal.read", "progress.read", "analytics.read"],
  case_manager: [
    "student.read",
    "iep.manage",
    "goal.manage",
    "goal.read",
    "progress.enter",
    "progress.read",
    "analytics.read",
  ],
  paraprofessional: ["student.read", "goal.read", "progress.enter", "progress.read"],
  read_only_reviewer: ["student.read", "goal.read", "progress.read", "analytics.read"],
};
