import type { PermissionCode, RoleCode } from "@/lib/supabase/types";

export const ROLE_CODES = [
  "platform_admin",
  "organization_admin",
  "district_sped_admin",
  "building_admin",
  "program_admin",
  "intervention_specialist",
  "special_education_teacher",
  "related_service_provider",
  "school_psychologist",
  "case_manager",
  "paraprofessional",
  "read_only_reviewer",
] as const satisfies readonly RoleCode[];

export const PERMISSION_CODES = [
  "org.manage",
  "org.members.manage",
  "org.audit.read",
  "school.manage",
  "program.manage",
  "classroom.manage",
  "staff.assign",
  "student.create",
  "student.edit",
  "student.archive",
  "student.read",
  "iep.manage",
  "goal.manage",
  "goal.read",
  "progress.enter",
  "progress.finalize",
  "progress.read",
  "analytics.read",
  "report.period.manage",
  "report.draft",
  "report.review",
  "report.finalize",
  "report.read",
  "report.export",
  "behavior.define",
  "behavior.observe",
  "behavior.finalize",
  "behavior.read",
  "behavior.configure",
  "fba.manage",
  "fba.read",
  "intervention.library.manage",
  "intervention.plan.manage",
  "intervention.plan.activate",
  "intervention.fidelity.enter",
  "intervention.fidelity.finalize",
  "intervention.dosage.enter",
  "intervention.review",
  "intervention.read",
  "accommodation.library.manage",
  "accommodation.manage",
  "accommodation.implement",
  "accommodation.read",
  "service.definition.manage",
  "service.plan.manage",
  "service.plan.activate",
  "service.log.enter",
  "service.log.finalize",
  "service.read",
  "service.export",
  "contact.manage",
  "contact.read",
  "communication.enter",
  "communication.finalize",
  "communication.read",
  "communication.template.manage",
  "communication.internal.read",
  "meeting.manage",
  "meeting.finalize",
  "meeting.read",
  "meeting.type.manage",
  "classroom.schedule.manage",
  "classroom.operations.read",
  "routine.manage",
  "task_analysis.manage",
  "ef.plan.manage",
  "ef.observe",
  "ef.read",
  "checklist.manage",
  "checklist.respond",
  "staff.duty.assign",
  "daily_note.enter",
  "daily_note.finalize",
  "daily_note.read",
  "reinforcement.manage",
  "announcement.manage",
  "admin.intelligence.read",
  "admin.export",
  "admin.audit.read",
] as const satisfies readonly PermissionCode[];

export const ROLE_LABELS: Record<RoleCode, string> = {
  platform_admin: "Platform administrator",
  organization_admin: "Organization administrator",
  district_sped_admin: "District special education administrator",
  building_admin: "Building administrator",
  program_admin: "Program administrator",
  intervention_specialist: "Intervention specialist",
  special_education_teacher: "Special education teacher",
  related_service_provider: "Related service provider",
  school_psychologist: "School psychologist",
  case_manager: "Case manager",
  paraprofessional: "Paraprofessional",
  read_only_reviewer: "Read-only reviewer",
};

export const PERMISSION_LABELS: Record<PermissionCode, string> = {
  "org.manage": "Manage organization",
  "org.members.manage": "Manage memberships",
  "org.audit.read": "Read audit events",
  "school.manage": "Manage schools",
  "program.manage": "Manage programs",
  "classroom.manage": "Manage classrooms",
  "staff.assign": "Assign staff",
  "student.create": "Create students",
  "student.edit": "Edit students",
  "student.archive": "Archive students",
  "student.read": "Read students",
  "iep.manage": "Manage IEP cycles",
  "goal.manage": "Manage goals",
  "goal.read": "Read goals",
  "progress.enter": "Enter progress data",
  "progress.finalize": "Finalize progress data",
  "progress.read": "Read progress data",
  "analytics.read": "Read analytics",
  "report.period.manage": "Manage reporting periods",
  "report.draft": "Draft progress reports",
  "report.review": "Review progress reports",
  "report.finalize": "Finalize progress reports",
  "report.read": "Read progress reports",
  "report.export": "Export progress reports",
  "behavior.define": "Define behaviors",
  "behavior.observe": "Record behavior observations",
  "behavior.finalize": "Finalize behavior observations",
  "behavior.read": "Read behavior data",
  "behavior.configure": "Configure behavior settings",
  "fba.manage": "Manage FBA workspaces",
  "fba.read": "Read FBA workspaces",
  "intervention.library.manage": "Manage intervention library",
  "intervention.plan.manage": "Manage intervention plans",
  "intervention.plan.activate": "Activate intervention plans",
  "intervention.fidelity.enter": "Enter fidelity data",
  "intervention.fidelity.finalize": "Finalize fidelity data",
  "intervention.dosage.enter": "Enter dosage data",
  "intervention.review": "Review interventions",
  "intervention.read": "Read interventions",
  "accommodation.library.manage": "Manage accommodation library",
  "accommodation.manage": "Manage accommodations",
  "accommodation.implement": "Implement accommodations",
  "accommodation.read": "Read accommodations",
  "service.definition.manage": "Manage service definitions",
  "service.plan.manage": "Manage service plans",
  "service.plan.activate": "Activate service plans",
  "service.log.enter": "Enter service logs",
  "service.log.finalize": "Finalize service logs",
  "service.read": "Read services",
  "service.export": "Export services",
  "contact.manage": "Manage contacts",
  "contact.read": "Read contacts",
  "communication.enter": "Enter communications",
  "communication.finalize": "Finalize communications",
  "communication.read": "Read communications",
  "communication.template.manage": "Manage communication templates",
  "communication.internal.read": "Read internal communications",
  "meeting.manage": "Manage meetings",
  "meeting.finalize": "Finalize meetings",
  "meeting.read": "Read meetings",
  "meeting.type.manage": "Manage meeting types",
  "classroom.schedule.manage": "Manage classroom schedules",
  "classroom.operations.read": "Read classroom operations",
  "routine.manage": "Manage routines",
  "task_analysis.manage": "Manage task analyses",
  "ef.plan.manage": "Manage executive function plans",
  "ef.observe": "Observe executive function supports",
  "ef.read": "Read executive function supports",
  "checklist.manage": "Manage checklists",
  "checklist.respond": "Respond to checklists",
  "staff.duty.assign": "Assign staff duties",
  "daily_note.enter": "Enter daily notes",
  "daily_note.finalize": "Finalize daily notes",
  "daily_note.read": "Read daily notes",
  "reinforcement.manage": "Manage reinforcement systems",
  "announcement.manage": "Manage announcements",
  "admin.intelligence.read": "Read administrative intelligence",
  "admin.export": "Export administrative summaries",
  "admin.audit.read": "Read administrative audit activity",
};

const PHASE_13_ADMIN_PERMISSIONS = [
  "accommodation.library.manage",
  "accommodation.manage",
  "accommodation.implement",
  "accommodation.read",
  "service.definition.manage",
  "service.plan.manage",
  "service.plan.activate",
  "service.log.enter",
  "service.log.finalize",
  "service.read",
  "service.export",
] as const satisfies readonly PermissionCode[];

const PHASE_14_ADMIN_PERMISSIONS = [
  "contact.manage",
  "contact.read",
  "communication.enter",
  "communication.finalize",
  "communication.read",
  "communication.template.manage",
  "communication.internal.read",
  "meeting.manage",
  "meeting.finalize",
  "meeting.read",
  "meeting.type.manage",
] as const satisfies readonly PermissionCode[];

const PHASE_15_ADMIN_PERMISSIONS = [
  "classroom.schedule.manage",
  "classroom.operations.read",
  "routine.manage",
  "task_analysis.manage",
  "ef.plan.manage",
  "ef.observe",
  "ef.read",
  "checklist.manage",
  "checklist.respond",
  "staff.duty.assign",
  "daily_note.enter",
  "daily_note.finalize",
  "daily_note.read",
  "reinforcement.manage",
  "announcement.manage",
] as const satisfies readonly PermissionCode[];

/**
 * Mirrors the grants in the roles/permissions migrations.
 * Authorization still comes from RLS/RPC checks; this matrix is documentation
 * and a UI affordance for showing expected capabilities.
 */
export const ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionCode[]> = {
  platform_admin: [],
  organization_admin: PERMISSION_CODES,
  district_sped_admin: [
    "admin.intelligence.read",
    "admin.export",
    "admin.audit.read",
    "org.audit.read",
    "school.manage",
    "program.manage",
    "classroom.manage",
    "staff.assign",
    "student.create",
    "student.edit",
    "student.archive",
    "student.read",
    "iep.manage",
    "goal.manage",
    "goal.read",
    "progress.enter",
    "progress.finalize",
    "progress.read",
    "analytics.read",
    "report.period.manage",
    "report.draft",
    "report.review",
    "report.finalize",
    "report.read",
    "report.export",
    "behavior.define",
    "behavior.observe",
    "behavior.finalize",
    "behavior.read",
    "behavior.configure",
    "fba.manage",
    "fba.read",
    "intervention.library.manage",
    "intervention.plan.manage",
    "intervention.plan.activate",
    "intervention.fidelity.enter",
    "intervention.fidelity.finalize",
    "intervention.dosage.enter",
    "intervention.review",
    "intervention.read",
    ...PHASE_13_ADMIN_PERMISSIONS,
    ...PHASE_14_ADMIN_PERMISSIONS,
    ...PHASE_15_ADMIN_PERMISSIONS,
  ],
  building_admin: [
    "admin.intelligence.read",
    "school.manage",
    "classroom.manage",
    "staff.assign",
    "student.create",
    "student.edit",
    "student.read",
    "goal.read",
    "progress.read",
    "analytics.read",
    "report.read",
    "report.review",
    "behavior.observe",
    "behavior.read",
    "fba.manage",
    "fba.read",
    "intervention.plan.manage",
    "intervention.plan.activate",
    "intervention.fidelity.finalize",
    "intervention.review",
    "intervention.read",
    "accommodation.read",
    "service.read",
    "service.log.enter",
    "contact.manage",
    "contact.read",
    "communication.enter",
    "communication.finalize",
    "communication.read",
    "communication.internal.read",
    "meeting.manage",
    "meeting.finalize",
    "meeting.read",
    "classroom.schedule.manage",
    "classroom.operations.read",
    "routine.manage",
    "task_analysis.manage",
    "ef.read",
    "checklist.manage",
    "staff.duty.assign",
    "daily_note.read",
    "announcement.manage",
  ],
  program_admin: [
    "admin.intelligence.read",
    "program.manage",
    "classroom.manage",
    "staff.assign",
    "student.create",
    "student.edit",
    "student.read",
    "iep.manage",
    "goal.manage",
    "goal.read",
    "progress.enter",
    "progress.finalize",
    "progress.read",
    "analytics.read",
    "report.draft",
    "report.review",
    "report.read",
    "report.finalize",
    "behavior.define",
    "behavior.observe",
    "behavior.finalize",
    "behavior.read",
    "fba.manage",
    "fba.read",
    "intervention.library.manage",
    "intervention.plan.manage",
    "intervention.plan.activate",
    "intervention.fidelity.enter",
    "intervention.fidelity.finalize",
    "intervention.dosage.enter",
    "intervention.review",
    "intervention.read",
    "accommodation.manage",
    "accommodation.implement",
    "accommodation.read",
    "service.plan.manage",
    "service.log.enter",
    "service.log.finalize",
    "service.read",
    ...PHASE_14_ADMIN_PERMISSIONS,
    ...PHASE_15_ADMIN_PERMISSIONS,
  ],
  intervention_specialist: [
    "student.read",
    "iep.manage",
    "goal.manage",
    "goal.read",
    "progress.enter",
    "progress.finalize",
    "progress.read",
    "analytics.read",
    "report.draft",
    "report.read",
    "report.finalize",
    "behavior.define",
    "behavior.observe",
    "behavior.finalize",
    "behavior.read",
    "fba.manage",
    "fba.read",
    "intervention.library.manage",
    "intervention.plan.manage",
    "intervention.plan.activate",
    "intervention.fidelity.enter",
    "intervention.fidelity.finalize",
    "intervention.dosage.enter",
    "intervention.review",
    "intervention.read",
    "accommodation.manage",
    "accommodation.implement",
    "accommodation.read",
    "service.plan.manage",
    "service.log.enter",
    "service.log.finalize",
    "service.read",
    "contact.manage",
    "contact.read",
    "communication.enter",
    "communication.finalize",
    "communication.read",
    "communication.template.manage",
    "communication.internal.read",
    "meeting.manage",
    "meeting.finalize",
    "meeting.read",
    "classroom.operations.read",
    "routine.manage",
    "task_analysis.manage",
    "ef.plan.manage",
    "ef.observe",
    "ef.read",
    "checklist.manage",
    "checklist.respond",
    "daily_note.enter",
    "daily_note.finalize",
    "daily_note.read",
    "reinforcement.manage",
  ],
  special_education_teacher: [
    "student.read",
    "goal.read",
    "progress.enter",
    "progress.read",
    "analytics.read",
    "report.draft",
    "report.read",
    "behavior.observe",
    "behavior.read",
    "fba.read",
    "intervention.fidelity.enter",
    "intervention.dosage.enter",
    "intervention.read",
    "accommodation.manage",
    "accommodation.implement",
    "accommodation.read",
    "service.log.enter",
    "service.read",
    "contact.read",
    "communication.enter",
    "communication.read",
    "meeting.read",
    "classroom.operations.read",
    "routine.manage",
    "task_analysis.manage",
    "ef.observe",
    "ef.read",
    "checklist.manage",
    "checklist.respond",
    "daily_note.enter",
    "daily_note.read",
    "reinforcement.manage",
    "announcement.manage",
  ],
  related_service_provider: [
    "student.read",
    "goal.read",
    "progress.enter",
    "progress.read",
    "analytics.read",
    "report.draft",
    "report.read",
    "behavior.observe",
    "behavior.read",
    "fba.read",
    "intervention.fidelity.enter",
    "intervention.dosage.enter",
    "intervention.read",
    "accommodation.read",
    "service.plan.manage",
    "service.log.enter",
    "service.log.finalize",
    "service.read",
    "contact.read",
    "communication.enter",
    "communication.read",
    "meeting.read",
    "ef.observe",
    "ef.read",
    "checklist.respond",
    "daily_note.enter",
    "daily_note.read",
  ],
  school_psychologist: [
    "student.read",
    "goal.read",
    "progress.read",
    "analytics.read",
    "report.read",
    "report.review",
    "behavior.define",
    "behavior.observe",
    "behavior.finalize",
    "behavior.read",
    "fba.read",
    "intervention.review",
    "intervention.read",
    "contact.read",
    "communication.enter",
    "communication.finalize",
    "communication.read",
    "communication.internal.read",
    "meeting.manage",
    "meeting.finalize",
    "meeting.read",
  ],
  case_manager: [
    "student.read",
    "iep.manage",
    "goal.manage",
    "goal.read",
    "progress.enter",
    "progress.read",
    "analytics.read",
    "report.draft",
    "report.read",
    "report.finalize",
    "behavior.define",
    "behavior.observe",
    "behavior.finalize",
    "behavior.read",
    "fba.manage",
    "fba.read",
    "intervention.plan.manage",
    "intervention.plan.activate",
    "intervention.fidelity.enter",
    "intervention.fidelity.finalize",
    "intervention.dosage.enter",
    "intervention.review",
    "intervention.read",
    "accommodation.manage",
    "accommodation.implement",
    "accommodation.read",
    "service.plan.manage",
    "service.log.enter",
    "service.log.finalize",
    "service.read",
    "contact.manage",
    "contact.read",
    "communication.enter",
    "communication.finalize",
    "communication.read",
    "communication.template.manage",
    "communication.internal.read",
    "meeting.manage",
    "meeting.finalize",
    "meeting.read",
    "classroom.operations.read",
    "routine.manage",
    "task_analysis.manage",
    "ef.plan.manage",
    "ef.observe",
    "ef.read",
    "checklist.manage",
    "checklist.respond",
    "daily_note.enter",
    "daily_note.finalize",
    "daily_note.read",
    "reinforcement.manage",
  ],
  paraprofessional: [
    "student.read",
    "goal.read",
    "progress.enter",
    "progress.read",
    "behavior.observe",
    "behavior.read",
    "intervention.fidelity.enter",
    "intervention.dosage.enter",
    "intervention.read",
    "accommodation.implement",
    "accommodation.read",
    "service.log.enter",
    "service.read",
    "communication.enter",
    "communication.read",
    "classroom.operations.read",
    "ef.observe",
    "ef.read",
    "checklist.respond",
    "daily_note.enter",
    "daily_note.read",
  ],
  read_only_reviewer: [
    "student.read",
    "goal.read",
    "progress.read",
    "analytics.read",
    "report.read",
    "behavior.read",
    "fba.read",
    "intervention.read",
    "accommodation.read",
    "service.read",
    "contact.read",
    "communication.read",
    "meeting.read",
    "classroom.operations.read",
    "ef.read",
    "daily_note.read",
  ],
};
